# -*- coding: utf-8 -*-
"""Ml_Supervice_heart_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yFHs2g_P3TgT_zVxz4pL2Mbs6K-hp2Wi

# **Load Liberary
**
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

"""# Load **dataFrame**"""
df = pd.read_csv(r'C:\Users\Abhishek\OneDrive\Machine_l\heart_deasese\heart.csv')

df

"""# **EDA**"""

sns.heatmap(df.corr(numeric_only= True), annot = True)

#check head
df.head()

# check info
df.info()

#check describe
df.describe()

df.shape



#check null
df.isnull().sum()

#check duplicate
df.duplicated().sum()

df['HeartDisease'].value_counts().plot(kind='bar')

#check how in which column present inside the dataset
df.columns

#check histplot of numerical column
numeric_col = ['Age', 'RestingBP', 'Cholesterol','MaxHR']
for col in numeric_col:
  plt.figure(figsize=(6,4))
  sns.histplot(df[col],kde = True,bins=20)

df['Cholesterol'].value_counts()

"""output is 172 member = 0 cholestrol this is not posible,it is wrong fill data ,then repalce the remainind member mean .
ex
"""

#find the mean without "0"  in cholesterol
ch_mean = df.loc[df['Cholesterol'] != 0,'Cholesterol'].mean()

ch_mean

#fill mean in place of "0"
df['Cholesterol']  = df['Cholesterol'].replace(0,ch_mean)
df['Cholesterol']  = df['Cholesterol'].round(2)

"""restingbp is not possible  = 0 in human being ,
then fill the 0 restingbp member replace to mean of remainig restingbp

"""



#check histplot of numerical column
numeric_col = ['Age', 'RestingBP', 'Cholesterol','MaxHR']
for col in numeric_col:
  plt.figure(figsize=(6,4))
  sns.histplot(df[col],kde = True,bins=20)



#check how many affected female and male from heartdisease
sns.countplot(x= df['Sex'],hue = df['HeartDisease'])



#check chestpain vs heartdisease
sns.countplot(x = df['ChestPainType'],hue = df['HeartDisease'])

#check fastingbp vs HeartDisease
sns.countplot(x = df['FastingBS'],hue = df['HeartDisease'])

df.columns

#check outlier by the help of boxplot
sns.boxplot(x = 'HeartDisease',y= 'Cholesterol',data = df)

#check Age vs Heartdisease by the help of violinplot
sns.violinplot(x='HeartDisease',y='Age',data=df)

#check correaltion of all numeric column by the help of heatmap
sns.heatmap(df.corr(numeric_only=True),annot=True )

df.head()

cat_col = df.select_dtypes(include = 'object').columns
cat_col

for col in cat_col:
  print(f'{col} : {df[col].unique()}')

"""# **Data preprocessing and Cleaning
**
"""

df_encode  = df.copy()

df_copy = pd.get_dummies(
    df_encode,
    cat_col,
    drop_first= True,
    dtype = int
)
df_copy.head()
df_encode = pd.get_dummies(df,drop_first=True)

df_copy.head()

df_copy.shape

#split X and y
X = df_copy.drop('HeartDisease',axis =1)
y = df_copy['HeartDisease']

#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X, y)
clf.fit(X,y)

y_predict = clf.predict(X_test)
y_predict.shape

comapre = pd.DataFrame({
    'Actual':y_test,
    'Predicted':y_predict
})
comapre.head(10)

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

cm = confusion_matrix(y_test, y_predict, labels=[0, 1])
cm

print("--- Confusion Matrix ---")
print(cm)
print(f"True Negatives (TN): {cm[0, 0]}")
print(f"False Positives (FP): {cm[0, 1]}")
print(f"False Negatives (FN): {cm[1, 0]}")
print(f"True Positives (TP):  {cm[1, 1]}\n")

# 6. Calculate Performance Metrics
print("--- Classification Metrics ---")
print(f"Accuracy:  {accuracy_score(y_test, y_predict):.2f}")
print(f"Precision: {precision_score(y_test, y_predict):.2f}")
print(f"Recall:    {recall_score(y_test, y_predict):.2f}")
print(f"F1-Score:  {f1_score(y_test, y_predict):.2f}")

df

df.columns

new_patient = pd.DataFrame([{
    'Age': 50,
    'Sex': 'M',
    'ChestPainType': 'ASY',
    'RestingBP': 110,
    'FastingBS': 1,
    'Cholesterol': 120,
    'RestingECG': 'Normal',
    'MaxHR': 172,
    'ExerciseAngina': 'N',
    'Oldpeak': 3.4,
    'ST_Slope': 'UP'
}])

# 2. Convert text columns to dummy variables (One-Hot Encoding)
new_patient_encoded = pd.get_dummies(new_patient, columns=['Sex','ChestPainType','RestingECG', 'ExerciseAngina','ST_Slope'])

# 3. Align columns with your original training data
# (Ensure kijiye ki X_train pehle se defined ho)
new_patient_ready = new_patient_encoded.reindex(columns=X_train.columns, fill_value=0)

# 4. Predict using your trained model
# (Ensure kijiye ki clf model pehle se trained ho)
prediction = clf.predict(new_patient_ready)
probability = clf.predict_proba(new_patient_ready)[:, 1]

print(f"Predicted Class: {prediction[0]}")
print(f"Probability of being Positive: {probability[0]:.2f}")

# Save the trained model to a file
import joblib
joblib.dump(clf, 'logistic_regression_model.pkl')
print("Model saved successfully using joblib!")